#pragma once
#include <cstdint>

constexpr char transition_states[][48] = 
{
		"TRANSITION_STATE_EMPTY",
		"Singleplayer Swoop Up",
		"Multiplayer Swoop Up",
		"Creator Swoop Up",
		"Pre-HUD Checks",
		"Wait HUD Exit",
		"Wait For Summon",
		"Singleplayer Swoop Down",
		"Multiplayer Swoop Down",
		"Cancel Joining",
		"Retry Loading",
		"Retry Loading Slot 1",
		"Retry Loading Slot 2",
		"Retry Loading Slot 3",
		"Retry Loading Slot 4",
		"Wait On Invite",
		"Prejoining Freemode Session Checks",
		"Look For Fresh Join Freemode",
		"Look To Join Another Session Freemode",
		"Confirm Freemode Session Joining",
		"Wait Join Freemode Session",
		"Creation Enter Session",
		"Pre-Freemode Launch Script",
		"Freemode Teamfull Check",
		"Start Freemode Launch Script",
		"Freemode Transition Create Player",
		"Is Freemode And Transition Ready",
		"Freemode Swoop Down",
		"Post Bink Video Warp",
		"Freemode Final Setup Player",
		"Move Freemode To Running State",
		"Freemode How To Terminate",
		"Start Creator Pre-Launch Script Check",
		"Start Creator Launch Script",
		"Creator Transition Create Player",
		"Is Creator And Transition Ready",
		"Creator Swoop Down",
		"Creator Final Setup Player",
		"Move Creator To Running State",
		"Prejoining Testbed Session Checks",
		"Look For Fresh Join Testbed",
		"Look For Fresh Host Testbed",
		"Look To Join Another Session Testbed",
		"Look To Host Session Testbed",
		"Confirm Testbed Session Joining",
		"Wait Join Testbed Session",
		"Start Testbed Launch Script",
		"Testbed Transition Create Player",
		"Is Testbed And Transition Ready",
		"Testbed Swoop Down",
		"Testbed Final Setup Player",
		"Move Testbed To Running State",
		"Testbed How To Terminate",
		"Quit Current Session Prompt",
		"Wait For Transition Session To Setup",
		"Terminate Singleplayer",
		"Wait Terminate Singleplayer",
		"Kick Terminate Session",
		"Terminate Session",
		"Wait Terminate Session",
		"Terminate Session And Hold",
		"Terminate Session And Move Into Holding State",
		"Team Swapping Checks",
		"Return To Singleplayer",
		"Wait For Singleplayer To Start",
		"Waiting For External Termination Call",
		"Terminate Maintransition",
		"Wait For Dirty Load Confirm",
		"DLC Intro Bink",
};

const std::string blocked_scripts[] =
{
	"DISABLED-MainTransition",
	"DISABLED-cellphone_controller"
};
